### ISSUE TITLE
Add a note that you have to escape the slash in SECRET_KEY

### ISSUE THREAD

**Issue by lukepighetti** [vinid223/GcloudStorage-docker#2]
I believe most secret keys follow this format: `xxxxxxx/xxxxxxxxxxxxxxxxxxxxx`, however, you get a `sed` error unless you escape it with `xxxxxxx\/xxxxxxxxxxxxxxxxxxxxx`

**Comment by vinid223** [comment]
Thanks for the information. Sorry for the late response.

I'll be working on a rework of the image. Cron just seem to not work properly and google-cloud-sdk is behaving strangely in cron environment. I'll let you know when I have a testing image.

**Comment by vinid223** [comment]
Hello @lukepighetti 

I've just added a beta tag [V1.3-beta](https://hub.docker.com/layers/gcloud-storage-backup/vinid223/gcloud-storage-backup/V1.3-beta/images/sha256-f84d85c6e9803ccb044f27c18bb1c76fb3162903545807aba8c4ffcd3b4055a8?context=repo) 

I now use an other sed character for setting the value `|`

I'll be testing on my side too. Just let me know if you have issues or any other feedback.
