### ISSUE TITLE
No logs coming from cron

### ISSUE THREAD

**Issue by lukepighetti** [vinid223/GcloudStorage-docker#3]
I have a cron setup to run every minute for testing purposes, no files are being uploaded, but there are also no logs describing any errors.

**Comment by vinid223** [comment]
Thanks for the information. Sorry for the late response.

I'll be working on a rework of the image. Cron just seem to not work properly and google-cloud-sdk is behaving strangely in cron environment. I'll let you know when I have a testing image.

**Comment by vinid223** [comment]
Hello @lukepighetti 

I've just added a beta tag [V1.3-beta](https://hub.docker.com/layers/gcloud-storage-backup/vinid223/gcloud-storage-backup/V1.3-beta/images/sha256-f84d85c6e9803ccb044f27c18bb1c76fb3162903545807aba8c4ffcd3b4055a8?context=repo) 

It should show more logs now while running the backup.

I'll be testing on my side too. Just let me know if you have issues or any other feedback.
